function [BW,maskedImage] = segmentImage_v2(X,s,i)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 10-Dec-2021
%----------------------------------------------------


% Adjust data to span data range.
X = imadjust(X);

% Threshold image - adaptive threshold
BW = imbinarize(X, 'adaptive', 'Sensitivity', s, 'ForegroundPolarity', 'bright');

% Active contour
iterations = floor(i);
BW = activecontour(X, BW, iterations, 'Chan-Vese');

% Dilate mask with line
length = 3.000000;
angle = 0.000000;
se = strel('line', length, angle);
BW = imdilate(BW, se);

% Fill holes
BW = imfill(BW, 'holes');

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

